### ISSUE TITLE
airdrop_leak undefined symbol: X509_NAME_hash

### ISSUE THREAD

**Issue by TiborUdvari** [hexway/apple_bleee#39]
After I got owl working with an active monitor mode, this is a the error I'm getting when trying to launch `airdrop_leak`. I don't know how to debug this, please help. 

```
Traceback (most recent call last):
  File "/home/kali/Developer/apple_bleee/airdrop_leak.py", line 22, in <module>
    from opendrop2.cli import AirDropCli
  File "/home/kali/Developer/apple_bleee/opendrop2/cli.py", line 30, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "/home/kali/Developer/apple_bleee/opendrop2/client.py", line 32, in <module>
    from .util import AirDropUtil, AbsArchiveWrite
  File "/home/kali/Developer/apple_bleee/opendrop2/util.py", line 57, in <module>
    from ctypescrypto import cms, x509, pkey, oid
  File "/usr/local/lib/python3.10/dist-packages/ctypescrypto/cms.py", line 18, in <module>
    from ctypescrypto.x509 import StackOfX509
  File "/usr/local/lib/python3.10/dist-packages/ctypescrypto/x509.py", line 731, in <module>
    libcrypto.X509_NAME_hash.restype = c_long
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/arm-linux-gnueabihf/libcrypto.so.3: undefined symbol: X509_NAME_hash. Did you mean: 'X509_NAME_cmp'?
```

**Comment by afuen010** [comment]
> After I got owl working with an active monitor mode, this is a the error I'm getting when trying to launch `airdrop_leak`. I don't know how to debug this, please help.
> 
> ```
> Traceback (most recent call last):
>   File "/home/kali/Developer/apple_bleee/airdrop_leak.py", line 22, in <module>
>     from opendrop2.cli import AirDropCli
>   File "/home/kali/Developer/apple_bleee/opendrop2/cli.py", line 30, in <module>
>     from .client import AirDropBrowser, AirDropClient
>   File "/home/kali/Developer/apple_bleee/opendrop2/client.py", line 32, in <module>
>     from .util import AirDropUtil, AbsArchiveWrite
>   File "/home/kali/Developer/apple_bleee/opendrop2/util.py", line 57, in <module>
>     from ctypescrypto import cms, x509, pkey, oid
>   File "/usr/local/lib/python3.10/dist-packages/ctypescrypto/cms.py", line 18, in <module>
>     from ctypescrypto.x509 import StackOfX509
>   File "/usr/local/lib/python3.10/dist-packages/ctypescrypto/x509.py", line 731, in <module>
>     libcrypto.X509_NAME_hash.restype = c_long
>   File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
>     func = self.__getitem__(name)
>   File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: /lib/arm-linux-gnueabihf/libcrypto.so.3: undefined symbol: X509_NAME_hash. Did you mean: 'X509_NAME_cmp'?
> ```

I’m having this same issue. Have you figured it out?

**Comment by TiborUdvari** [comment]
I haven't managed to get it to work, let me know if you figure it out, please.

**Comment by fuad00** [comment]
Any updates?

**Comment by steev** [comment]
I believe this is actually an issue with ctypescrypto, and newer openssl and not apple_blee's code itself

**Comment by szhyt** [comment]
There is the same problem. If it is resolved, please publicize the solution. Thank you

**Comment by secu77** [comment]
I have the same error. I tried to fix it by installing an older version of openssl and linking it to Python, but it didn't work:

```
# Installing OpenSSL 1.1.1v
wget https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1v/openssl-1.1.1v.tar.gz
tar zxf openssl-1.1.1v.tar.gz
cd openssl-1.1.1v
./config --prefix=/usr/src/lib --openssldir=/usr/src/lib/ssl
make
make install
cd ..

# Installing Python3.8 and linking openssl lib
wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
tar xf Python-3.8.0.tgz
cd Python-3.8.0
LDFLAGS="${LDFLAGS} -Wl,-rpath=/usr/src/lib/lib" ./configure --with-openssl=/usr/src/lib
make
make install
```

I may have missed something or made a mistake, I don't know. If you know anything, it would be nice to know.

**Comment by mmotwicki** [comment]
Same thing, didn't managed to get it to work

**Comment by steev** [comment]
> I have the same error. I tried to fix it by installing an older version of openssl and linking it to Python, but it didn't work:
> 
> ```
> # Installing OpenSSL 1.1.1v
> wget https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1v/openssl-1.1.1v.tar.gz
> tar zxf openssl-1.1.1v.tar.gz
> cd openssl-1.1.1v
> ./config --prefix=/usr/src/lib --openssldir=/usr/src/lib/ssl
> make
> make install
> cd ..
> 
> # Installing Python3.8 and linking openssl lib
> wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
> tar xf Python-3.8.0.tgz
> cd Python-3.8.0
> LDFLAGS="${LDFLAGS} -Wl,-rpath=/usr/src/lib/lib" ./configure --with-openssl=/usr/src/lib
> make
> make install
> ```
> 
> I may have missed something or made a mistake, I don't know. If you know anything, it would be nice to know.

The issue is ctypescrypto not apple_bleee - rebuild ctypescrypto against the older openssl
